name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: app

    - name: Run application (build step)
      run: echo "Application ready for deployment!"

    - name: Deploy to EC2 (example step)
      run: echo "Connect to EC2 and deploy manually or using Ansible."
